<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <Import Project="..\..\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" />

  <Target Name="CopyFiles" BeforeTargets="PrepareForBuild">
    <Copy SourceFiles="..\Violate-Analyzers.ps1" DestinationFolder="$(MSBuildThisFileDirectory)" />
  </Target>

</Project>
