name: PowerShell Static Code Analysis

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  powershell-static-code-analysis:
    name: PowerShell Static Code Analysis
    uses: Lombiq/PowerShell-Analyzers/.github/workflows/static-code-analysis.yml@issue/OSOE-504
    with:
      # Making sure that analysis runs through both PowerShell editions regardless of the default configuration of the
      # workflow and the underlying action to ensure backwards-compatibility.
      run-windows-powershell: "true"
      run-powershell-core: "true"
