name: Validate NuGet Publish

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  validate-nuget-publish:
    name: Validate NuGet Publish
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-nuget-publish.yml@dev
    with:
      # These warnings are related to the tooling erroneously assuming that a ps1 file must be an (un)install script. In
      # this repo the ps1 files are assets to be used by the consumer.
      dotnet-pack-ignore-warning: NU5110 NU5111
